server.port=8082
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/bankcore_db
spring.datasource.username=bankcore
spring.datasource.password=secret
#Hibernate crée/modifie les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Formate le SQL pour le rendre lisible
spring.jpa.properties.hibernate.format_sql=true

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/bankcore

# Feign
client-service.url=http://localhost:8081

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security
## \u2192 Évite la page "Please sign in" au démarrage
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration